directory: ~/Dropbox/Songs/
format_item: $artist - $composer - $album - $title - $genre - $year - $path
library: /var/tmp/musiclibrary.blb
import:
    copy: no
    write: no
    autotag: no
plugins: edit info smartplaylist fromfilename mbcollection
lastfm:
    user: muralisc
smartplaylist:
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: all.m3u
          query: 'last_played:..2016-04-17'
        - name: Hindi.m3u
          query: 'path::Hindi last_played:..2016-04-17'
        - name: English.m3u
          query: 'path::English last_played:..2016-04-17'
edit:
    itemfields: track title artist album lyrics
lyrics:
    auto: yes
