directory: ~/Dropbox/Songs/
library: ~/Dropbox/Songs/musiclibrary.blb
import:
    copy: no
    write: yes
plugins: edit lastimport smartplaylist mpdstats
lastfm:
    user: muralisc
smartplaylist:
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: all.m3u
          query: 'last_played:..2016-04-17'
        - name: Hindi.m3u
          query: 'path::Hindi last_played:..2016-04-17'
        - name: English.m3u
          query: 'path::English last_played:..2016-04-17'
edit:
    itemfields: track title artist album lyrics
lyrics:
    auto: yes
