directory: ~/Dropbox/Songs/
library: ~/Dropbox/Songs/musiclibrary.blb
import:
    copy: no
    write: yes
plugins: edit lastimport smartplaylist mpdstats
lastfm:
    user: muralisc
smartplaylist:
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: all.m3u
          query: 'path::English'
edit:
    itemfields: track title artist album lyrics
lyrics:
    auto: yes
